name: CI

on:
  pull_request:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint
        run: shellcheck bin/podfiles

  unit-tests:
    name: Bats tests
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - name: Install bats & curl
        run: |
          sudo apt-get update
          sudo apt-get install -y bats curl
      - name: Run unit tests
        run: bats -r tests

  docker-tools-check:
    name: Netshoot tooling check
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Pre-pull netshoot (reduce flakes)
        run: docker pull nicolaka/netshoot:latest
      - name: Install bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run netshoot test
        run: |
          # Only run the docker-based test file (if you added it)
          if [ -f tests/test_netshoot_tooling.bats ]; then
            bats tests/test_netshoot_tooling.bats
          else
            echo "tests/test_netshoot_tooling.bats not found; skipping"
          fi
