name: Gatekeeper
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  checks: read
  pull-requests: read
  statuses: read

concurrency:
  group: gatekeeper-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  gatekeeper:
    if: ${{ github.event.pull_request.base.ref == github.event.repository.default_branch }}
    runs-on: self-hosted
    steps:
      - name: Wait for required checks to succeed
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          checks-name: >
            ShellCheck,
            Bats tests,
            Conventional PR Title,
            Bump Guard (Title ≥ Commits)
          ref: ${{ github.event.pull_request.head.sha }}
          wait-interval: 30
          allowed-conclusions: success
      - name: All required checks passed
        run: echo "✅ Gatekeeper all checks succeeded."
